all:
  rpiz_cams_gs:
    hosts: 127.0.0.1
    connection: local
  children:
    rpiz_cams_group:
      vars:
        ansible_connection: ssh
        ansible_user: pi
        ansible_password: raspberry
      children:
        rpiz_cams_v1_group:
          hosts:
            stream01:
              ansible_host: 10.0.0.51
            stream02:
              ansible_host: 10.0.0.52
            stream03:
              ansible_host: 10.0.0.53
            stream04:
              ansible_host: 10.0.0.54
          vars: 
            ustreamer_resolution: 640x480
        rpi_cams_v2_group:
          hosts:        
            stream05:
              ansible_host: 10.0.0.55
            stream06:
              ansible_host: 10.0.0.56
          vars:
            ustreamer_resolution: 1280x720
